users:
  rows: 50
  fields:
    id: uuid
    first_name: faker.person.firstName
    last_name: faker.person.lastName
    user_mail: string # Smart-inferred to email
    is_active: boolean
    created_at: date

orders:
  rows: 200
  fields:
    order_id: uuid
    user_id: ref(users.id) # Topologically sorted dependency
    amount: number
    status: faker.word.sample
    shipping_address: location.streetAddress
